### ISSUE TITLE
[問題] 此專案將來走向

### ISSUE THREAD

**Issue by CollieIsCute** [glepnir/nvim-lua-guide-zh#17]
[原文專案 (nvim-lua-guide)](https://github.com/nanotee/nvim-lua-guide) 已經 public archieve, 請問此專案後續會跟著一起 public archieve, 還是會以[新的 document (官網)](https://neovim.io/doc/user/lua-guide.html#lua-guide)來繼續翻譯呢？

**Comment by glepnir** [comment]
因为我们已经在neovim中内置了lua 教程 你可以使用head版本的neovim `:h lua-guide` . 这个repo的上游应该不会更新了。
