### ISSUE TITLE
请问neovim处理字符宽度有什么技巧吗

### ISSUE THREAD

**Issue by JuanZoran** [glepnir/nvim-lua-guide-zh#19]
最近想写一个翻译插件，格式化排版，计算窗口wrap后的高度，用的这样一个函数
```lua
local function get_height(bufnr, winid)
    if not vim.wo[winid].wrap then
        return vim.api.nvim_buf_line_count(bufnr)
    end

    local width = vim.api.nvim_win_get_width(winid)


    local lines = vim.api.nvim_buf_get_lines(bufnr, 0, -1, false)
    local height = 0
    for i = 1, #lines do
        height = height + math.max(1, (math.ceil(vim.fn.strdisplaywidth(lines[i]) / width)))
    end
    return height
end
```
计算结果总是不符合预期, 使用`vim.fn.strdisplaywidth和`vim.fn.strwidth` 结果相同

**Comment by JuanZoran** [comment]
测试`vim.fn.strdisplaywidth`和`vim.fn.strwidth`都是获得111, 看右下角的ruler能知道宽度是112
貌似是这样造成height 出现偏差
![Screenshot_20230114_134853](https://user-images.githubusercontent.com/107862700/212458157-481b7e60-7f2d-4291-b845-6d9d8f698f73.png)
![Screenshot_20230114_134930](https://user-images.githubusercontent.com/107862700/212458160-333a6589-0983-4032-a330-eedcf75b9034.png)

**Comment by glepnir** [comment]
ascii 字符 和emoji 之类的字符宽度是不同的。emoji之类的可能是3个。 nvim_strwidth strdisplaywidth 差不多
